# Generated by Django 4.2.7 on 2024-07-27 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityNamesCheckListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(default=1, verbose_name='priority')),
                ('name', models.CharField(max_length=50, verbose_name='activity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'apps_project_spirit_activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityTimeEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(default=1, verbose_name='priority')),
                ('completed_at_date', models.DateField(verbose_name='completed date')),
                ('completed_at_time', models.TimeField(verbose_name='completed time')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
            ],
            options={
                'verbose_name': 'Activity time entry',
                'verbose_name_plural': 'Activity time entries',
                'db_table': 'apps_project_spirit_activity_time_entry',
            },
        ),
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(default=1, verbose_name='priority')),
                ('flight_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Flight name')),
                ('flight_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Flight number')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'db_table': 'apps_project_spirit_flight',
            },
        ),
        migrations.CreateModel(
            name='RampDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(default=1, verbose_name='priority')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('license_plate', models.CharField(max_length=10, verbose_name='license plate')),
                ('winery_1_open', models.TimeField(verbose_name='winery 1 open')),
                ('winery_1_closure', models.TimeField(verbose_name='winery 1 clousure')),
                ('first_unloading_of_luggage', models.TimeField(verbose_name='first unloading of luggage')),
                ('last_unloading_of_luggage', models.TimeField(verbose_name='last unloading of luggage')),
                ('arrival_of_the_first_baggage_shipping', models.TimeField(verbose_name='arrival of the first baggage shipping')),
                ('arrival_of_the_last_baggage_shipping', models.TimeField(verbose_name='arrival of the last baggage shipping')),
                ('rear_ladder_coupling_begins', models.TimeField(auto_now=True, verbose_name='rear ladder coupling begins')),
                ('rear_ladder_coupling_end', models.TimeField(auto_now=True, verbose_name='rear ladder coupling begins')),
                ('maintenance_arrival', models.TimeField(auto_now=True, verbose_name='maintenance arrival')),
                ('maintenance_output', models.TimeField(auto_now=True, verbose_name='maintenance output')),
                ('gasoline_arrival', models.TimeField(auto_now=True, verbose_name='terpel arrival')),
                ('gasoline_output', models.TimeField(auto_now=True, verbose_name='terpel output')),
                ('firefighters_in', models.TimeField(verbose_name='firefighters in')),
                ('firefighters_out', models.TimeField(verbose_name='firefighters out')),
                ('plant_coupling', models.TimeField(verbose_name='plant coupling')),
                ('plant_decoupling', models.TimeField(verbose_name='plant decoupling')),
                ('baggage_load_cp1', models.PositiveIntegerField(verbose_name='baggage load cp1')),
                ('airplane_tire_lock', models.TimeField(verbose_name='airplane tire lock')),
                ('airplane_push_back', models.TimeField(verbose_name='airplane push back')),
                ('baggage_shipping_1', models.CharField(max_length=10, verbose_name='baggage shipping 1 code and number')),
                ('baggage_shipping_1_total', models.PositiveIntegerField(verbose_name='baggage shipping 1 total')),
                ('seals_shipping_1', models.CharField(max_length=255, verbose_name='seals shipping 1')),
                ('baggage_shipping_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='baggage shipping 2 code and number')),
                ('baggage_shipping_2_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='baggage shipping 2 total')),
                ('seals_shipping_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='seals shipping 2')),
                ('baggage_shipping_3', models.CharField(blank=True, max_length=10, null=True, verbose_name='baggage shipping 3 code and number')),
                ('baggage_shipping_3_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='baggage shipping 3 total')),
                ('seals_shipping_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='seals shipping 3')),
                ('baggage_shipping_4', models.CharField(blank=True, max_length=10, null=True, verbose_name='baggage shipping 4 code and number')),
                ('baggage_shipping_4_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='baggage shipping 4 total')),
                ('seals_shipping_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='seals shipping 4')),
                ('taxiing', models.TimeField(verbose_name='taxiing')),
            ],
            options={
                'verbose_name': '2. Ramp One Data',
                'verbose_name_plural': '2. Ramp One Data',
                'db_table': 'apps_project_spirit_ramp_one_data',
            },
        ),
        migrations.CreateModel(
            name='UserActivityCheckListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(default=1, verbose_name='priority')),
                ('time_entries', models.ManyToManyField(blank=True, to='rampone.activitytimeentrymodel')),
            ],
            options={
                'verbose_name': '1. CheckList',
                'verbose_name_plural': '1. CheckList',
                'db_table': 'apps_project_spirit_user_activity_check_list',
            },
        ),
    ]
