# Generated by Django 4.2.7 on 2024-07-18 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rampone', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitychecklistmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rampdatamodel',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='rampdatamodel',
            name='flight_arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_arrival', to='rampone.flightmodel', verbose_name='Flight arrival'),
        ),
        migrations.AddField(
            model_name='rampdatamodel',
            name='flight_departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_departure', to='rampone.flightmodel', verbose_name='Flight departure'),
        ),
        migrations.AddField(
            model_name='activitytimeentrymodel',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='rampone.activitynameschecklistmodel', verbose_name='activity'),
        ),
    ]
