# Generated by Django 4.2.13 on 2024-07-27 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rampone', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitynameschecklistmodel',
            options={'verbose_name': '1.1 Activity', 'verbose_name_plural': '1.1 Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitytimeentrymodel',
            options={'verbose_name': '1.2 Activity time entry', 'verbose_name_plural': '1.2 Activity time entries'},
        ),
        migrations.AlterModelOptions(
            name='flightmodel',
            options={'verbose_name': '2.1 Flight', 'verbose_name_plural': '2.1 Flights'},
        ),
        migrations.AlterModelOptions(
            name='rampdatamodel',
            options={'verbose_name': '2.0 Ramp One Data', 'verbose_name_plural': '2.0 Ramp One Data'},
        ),
        migrations.AlterModelOptions(
            name='useractivitychecklistmodel',
            options={'verbose_name': '1.0 CheckList', 'verbose_name_plural': '1.0 CheckList'},
        ),
        migrations.AlterField(
            model_name='activitytimeentrymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitytimeentry_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
