# Generated by Django 4.2.7 on 2024-07-18 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampone', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightmodel',
            options={'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Flight name'),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Flight number'),
        ),
        migrations.AlterField(
            model_name='rampdatamodel',
            name='flight_arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_arrival', to='rampone.flightmodel', verbose_name='Flight arrival'),
        ),
        migrations.AlterField(
            model_name='rampdatamodel',
            name='flight_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_departure', to='rampone.flightmodel', verbose_name='Flight departure'),
        ),
        migrations.AlterModelTable(
            name='flightmodel',
            table='apps_project_spirit_flight',
        ),
    ]
