# Generated by Django 4.2.7 on 2024-08-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampone', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rampdatamodel',
            name='airplane_winery_inspection',
            field=models.TimeField(auto_now=True, verbose_name='airplane winery inspection'),
        ),
    ]
