# Generated by Django 4.2.7 on 2024-07-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampone', '0003_alter_flightmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Flight number'),
        ),
    ]
