# Generated by Django 4.2.7 on 2024-07-18 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampone', '0004_alter_flightmodel_flight_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitynameschecklistmodel',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitytimeentrymodel',
            options={'verbose_name': 'Activity time entry', 'verbose_name_plural': 'Activity time entries'},
        ),
        migrations.AlterModelOptions(
            name='rampdatamodel',
            options={'verbose_name': '2. Ramp One Data', 'verbose_name_plural': '2. Ramp One Data'},
        ),
        migrations.AlterModelOptions(
            name='useractivitychecklistmodel',
            options={'verbose_name': '1. CheckList', 'verbose_name_plural': '1. CheckList'},
        ),
        migrations.AlterField(
            model_name='rampdatamodel',
            name='flight_departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_departure', to='rampone.flightmodel', verbose_name='Flight departure'),
        ),
        migrations.AlterModelTable(
            name='activitynameschecklistmodel',
            table='apps_project_spirit_activities',
        ),
        migrations.AlterModelTable(
            name='activitytimeentrymodel',
            table='apps_project_spirit_activity_time_entry',
        ),
        migrations.AlterModelTable(
            name='useractivitychecklistmodel',
            table='apps_project_spirit_user_activity_check_list',
        ),
    ]
