# Generated by Django 4.2.7 on 2024-07-28 02:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaggageShippingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('cart_name', models.CharField(default='diligence ', max_length=50, verbose_name='cart name')),
                ('cart_code', models.CharField(max_length=5, verbose_name='cart code')),
                ('cart_number', models.PositiveIntegerField(verbose_name='cart number')),
                ('total_baggage', models.PositiveIntegerField(verbose_name='total baggage')),
            ],
            options={
                'verbose_name': '2.0 Baggage Shipping',
                'verbose_name_plural': '2.0 Baggage Shippings',
                'db_table': 'apps_project_spirit_baggage_shipping',
            },
        ),
        migrations.CreateModel(
            name='BaggageShippingSealsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('seal_number', models.PositiveIntegerField(verbose_name='seal number')),
                ('diligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggageshippingseals_baggageshipping', to='baggage.baggageshippingmodel', verbose_name='baggage shipping')),
            ],
            options={
                'verbose_name': '2.1 Seal',
                'verbose_name_plural': '2.1 Seals',
                'db_table': 'apps_project_spirit_baggage_shipping_seals',
            },
        ),
    ]
