# Generated by Django 4.2.13 on 2024-07-27 05:36

import apps.project.common.users.signals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.project.common.users.signals.avatar_directory_path, verbose_name='profile picture'),
        ),
    ]
