# Generated by Django 4.2.7 on 2024-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='employee_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
