# Generated by Django 4.2.7 on 2024-07-17 17:11

import apps.project.common.users.signals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.project.common.users.signals.avatar_directory_path, verbose_name='foto de perfil'),
        ),
    ]
