# Generated by Django 4.2.7 on 2024-06-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_cleaner',
        ),
    ]
