# Generated by Django 4.2.7 on 2024-07-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='employee_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
