# Generated by Django 4.2.7 on 2024-06-26 21:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='idioma')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='esta activo')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='prioridad')),
                ('names', models.CharField(max_length=150, verbose_name='names')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('title', models.CharField(max_length=50, verbose_name='subject')),
                ('message', models.TextField(verbose_name='mesage')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
