# Generated by Django 4.2.7 on 2024-06-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_contactmodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
    ]
