# Generated by Django 4.2.7 on 2024-07-01 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_contactmodel_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
        migrations.AlterModelTable(
            name='contactmodel',
            table='apps_project_page_contact',
        ),
    ]
