# Generated by Django 4.2.7 on 2024-07-28 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('flight_category', models.CharField(choices=[('D', 'Departure'), ('A', 'Arrival')], default=('A', 'Arrival'), max_length=50, verbose_name='category')),
                ('flight_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Flight name')),
                ('flight_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Flight number')),
            ],
            options={
                'verbose_name': '1.0 Flight',
                'verbose_name_plural': '1.0 Flights',
                'db_table': 'apps_project_spirit_flight',
                'unique_together': {('flight_category', 'flight_name', 'flight_number')},
            },
        ),
    ]
