# Generated by Django 4.2.7 on 2024-07-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_category',
            field=models.CharField(choices=[(None, 'Select One'), ('D', 'Departure'), ('A', 'Arrival')], default=('D', 'Departure'), max_length=50, verbose_name='category'),
        ),
    ]
